### ISSUE TITLE
Nan's und Programmabstürze der Matrix-Vektormultiplikation

### ISSUE THREAD

**Issue by joduen** [cdkh/68616564616C7573#10]
Beim Testen meiner gpu-operationen ist mir aufgefallen, dass die Standard Matrix-Vektor
Multiplikation für Dimensionen um ca. 100000 NANs liefert und bei
Dimensionen ab ca 1000000 das Programm abstürzt. Konnte das durch eine
zusätzliche if-Abfrage in defect() und matvec() lösen. Aber eigentlich
ist das so eher unschön. Vor allem weiß ich nicht, ob ich vielleicht
meine Matrix falsch gebaut hab (check_intact() liefert aber true). Könnt ja mal drüber gucken und/oder
versuchen die probleme bei euch zu reproduzieren. Was war denn bisher
die größte Testmatrix?

Hab dazu mal einen debug-branch angelegt und die entsprechenden Dateien commited. Mit der veränderten DIA.hpp in dem Branch scheint bei mir alles zu funktionieren.

**Comment by dandonner** [comment]
Meinst du die if-Abfrage sei eher unschön, oder was genau?
An und für sich verstehe ich, warum die Abfrage Sinn macht, hab das Problem bei mir bisher noch nicht gesehen, aber war auch glaube nicht so groß.
Wäre mal interessant zu wissen, ob Michi solche Problemgrößen bei sich hatte.

Edit: Bei welchem Test genau sind denn die Probleme aufgetreten?

**Comment by joduen** [comment]
Ja, ich meine die if-Abfrage. Wird so halt in jedem schritt durchgeführt und kostet Zeit. Ich dachte, dass man die vielleicht durch eine Änderung der for Schleifen vermeiden oder reduzieren kann.

**Comment by dandonner** [comment]
Kannst du noch was zum Testfall sagen, wo das aufgetreten ist?
Die Frage hatte ich oben in meine Anmerkung noch hinein editiert...

**Comment by joduen** [comment]
Im Branch joduen-debug ist die Datei zufallstest.cu In dem Testfall hatte ich NANs  und für den gleichen Testfall mit dim = 1000000 und dem offset Vektor (-1000, -1, 0, 1, 1000) ist es immer abgestürzt.

**Comment by joduen** [comment]
Hab das ganze gerade mal auf kashyyyk getestet: Für dim=1.000.000 und offset = (-10.000, -100, -1, 0, 1, 100, 10.000)  (sollte doch die struktur unseres 7-punkte-sterns sein (?) ) bekomme ich wie erwartet eine Speicherschutzverletzung ohne die if-Abfrage. Sollte also am Zugriff auf auf den x- Vektor liegen. Ich überlege mir mal noch, ob man das irgendwie anders lösen kann.

**Comment by dandonner** [comment]
So wie ich das sehe, ist dieses Problem nach derzeitigem Stand gelöst, deswegen werde ich das Problem mal schließen.
