### ISSUE TITLE
value Operator - Valgrind Speicherfehler

### ISSUE THREAD

**Issue by ghost** [cdkh/68616564616C7573#5]
Valgrind gibt mir den Fehler, dass bei dem Operator value(i,j) auf Speicher zugegriffen wird, der nicht fuer Matrix frei ist.

**Comment by heikop** [comment]
Gab eben bei Micha auch einen Fehler, wo die Funktion eingebaut war. Ich schau mir das heute noch an.

**Comment by joduen** [comment]
die for schleife darf nur bis _numDiags laufen ;) sonst greifst du auf offset[i] zu mit i > _numDiags

**Comment by heikop** [comment]
Ja. Habs auch eben gesehen. Ist geaendert.
Dafuer sind gute Tests da ;)

Ich schliesse dann mal.
