### ISSUE TITLE
Defekt-Funktion: Zusätzlicher Constructor-Aufruf

### ISSUE THREAD

**Issue by dandonner** [cdkh/68616564616C7573#6]
Wie schon bei einem commit angemerkt, schreibe ich das hier nochmal als zentrales Problem:
Wir müssen in der Defekt-Funktion den Hilfsvektor Ax umgehen, um keinen zusätzlichen Speicher zu belegen.
Irgendwelche Vorschläge?

**Comment by joduen** [comment]
template <typename datatype>
void defekt(Vector<datatype>& r, DIA<datatype>& A, Vector<datatype>& b, Vector<datatype>& x)
{
  if (r._dim!=A._dim || A._dim!=b._dim || b._dim!=x._dim) 
  {
     throw invalid_argument(" -Achtung! Dimensionsfehler!- ");
     }else{
       for (int i(0); i < A.dim(); ++i) {
         datatype resval(b[i]);
         for (int j(0); j < A.numDiags(); ++j) {
           resval -= (*A._data)[A.dim() \* j + i] \* x[i + A.offset()[j]];
         }
         r._data[i] = resval;
      }
   }
}

Wäre jetzt ein Vorschlag, habe aber gerade keine Zeit ihn zu testen. Idee ist einfach den SpMV mit -= statt += zu benutzten und die Werte r[i] vorher nicht auf 0 sondern auf b[i] zu initialisieren.  

Edit: wollte es nicht schließen, hab mich verklickt. kann es heute Abend testen und commiten falls es funktioniert und sinnvoll ist.

**Comment by dandonner** [comment]
Du solltest vllt die Initialisierung von resval vor die for-Schleife setzen und als 0 initialisieren und dann an der Stelle, wo es gerade ist, einfach "resval = b[i]" machen. Sonst sehe ich derzeit keine Probleme... 

Edit: mir ist gerade aufgefallen, dass das bei SpMV auch in jedem Schleifendurchlauf initialisiert wird, das sollte man da auch raus packen. Könnte mich auch wenn heute Abend drum kümmern.

Edit2: Ich frage mich gerade, ob man das resval überhaupt benötigt. Man könnte auch direkt r._data[i](bzw einfach r[i]) erst gleich b[i] setzen und dann -= machen, oder?

**Comment by heikop** [comment]
Das Problem ist, dass wir ja eigentlich ohne v2=A*v1 auskommen wollen, sondern stattdessen immer matvec(v2,A,v1) machen. Also koennte man es so machen:
else {
  matvec(r, A, x);
  r.skalarmult(-1);
  r.vecadd(b);
}

Das muesste auf obigen Vorschlag hinauslaufen, nur, dass das jetzt die schon vorhandenen Funktionen nutzt. Dadurch hat man allerdings den extra Schritt mit -1 zu multiplizieren.

Zu SpMV: Ja, ist mir auch schon aufgefallen. Aber laut Markus gibt es da ja eh noch eine andere bessere Loesung.

PS: skalarmult ist noch ein deutscher Name ;)
